# MAIN base
baseURL = "https://knowthychoice.in/"
languageCode = "en-us"
title = "KTC | Know Thy Choice"
theme = "apsho"

# Navigation Bar
[[menu.main]]
    name = "Home"
    url = "#hero"
    weight = 1
[[menu.main]]
    name = "Product"
    url = "#feature"
    weight = 2
[[menu.main]]
    name = "Mentors"
    url = "#mentors"
    weight = 3
[[menu.main]]
    name = "Programs"
    url = "#programs"
    weight = 4

# Footer Sitemap
[[menu.sitemap]]
    name = "Home"
    url = "#"
    weight = 1
[[menu.sitemap]]
    name = "Terms & Conditions"
    url = "/tnc"
    weight = 2
[[menu.sitemap]]
    name = "Privacy & Policy"
    url = "/privacy"
    weight = 3
[[menu.sitemap]]
    name = "Refund Policy"
    url = "/refund"
    weight = 4
[[menu.sitemap]]
    name = "Get In Touch"
    url = "/contact"
    weight = 5

# Footer Address
[params.address]
address = "#6 Artillary Road, Bengaluru, India"
email = "shipra@knowthychoice.in"
phone = "+91 626 878 8090"

# Footer Social
[params.social]
facebook = "https://www.facebook.com/pg/staticmania"
linkedin = "https://linkedin.com/knowthychoice"
github = "https://github.com/StaticMania"

[params]

# Header
logo = "images/logo.png"
formspreeURL = "https://formspree.io/mknyovwz"
googleAnalytics = "G-251ESPDTK1"

# Footer
footerTitle = "Get the latest updates"
copyright1 = "All right reserved"
copyright2 = "Copyright © KTC 2022 "

#contact
email = "shipra@knowthychoice.in"